# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d7d69f071bbe9e27be14a1a200b8c4ea5b3b2d981c94a82e54aa6293afe1c262935c1b907fbc9888f2fff4891f5150d1c5d4cb83f228e1d2a875eda462e070e

test:
  secret_key_base: c9eae61b667c26de3e963ce059edb0c138226514a4540b5bb3ea560b5d72c2ebf1a65bcc3e76afd97f15a8a806c061a98aab0e0f8a7adc2aa7590bccce14ec1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
